// Code generated by goctl. DO NOT EDIT.
package types

type BaseResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type DeviceConfigReq struct {
	DeviceId string `json:"deviceId"`
}

type DeviceConfigResp struct {
	BaseResp
	DeviceConfigId      string `json:"deviceConfigId"`
	DeviceConfigDetails string `json:"deviceConfigDetails"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	BaseResp
	Token string `json:"token"`
}
