// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	device "sprinkler/internal/handler/device"
	user "sprinkler/internal/handler/user"
	"sprinkler/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/config",
				Handler: device.DeviceConfigHandler(serverCtx),
			},
		},
		rest.WithPrefix("/device"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user"),
	)
}
